version: '3.8'

services:

  api:
    image: webcontainer12.azurecr.io/api:latest
    ports:
      - "4000:4000"

  web:
    image: webcontainer12.azurecr.io/web:latest
    ports:
      - "80:80"
    depends_on:
      - api