name: Deploy to Dev

on:
  push:
    branches:
      - develop

  workflow_dispatch:
    inputs:
      correlation_id:
        description: 'Unique identifier attached to workflow dispatch'
        required: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write

jobs:

  log-correlation-id:
    name: Print Correlation ID

    runs-on: ubuntu-latest

    steps:
      - name: Log Correlation ID
        run: |
          echo "Correlation ID: ${{ github.event.inputs.correlation_id }}"

  build-and-publish:
    name: Build and Publish Containers

    needs: [log-correlation-id]

    uses: ./.github/workflows/container-build-azure.yml

    with:
      ENVIRONMENT: dev

      BUILD_CONTEXT: >
        [
          {
            "path": ".",
            "image": "api",
            "dockerfile": "Dockerfile.api"
          },
          {
            "path": ".",
            "image": "web",
            "dockerfile": "Dockerfile.web"
          }
        ]

      TAG_NAME: ${{ format('dev-{0}', github.sha) }}

    secrets: inherit

  prep-deploy-matrix:
    name: Prepare Deploy Matrix

    runs-on: ubuntu-latest

    needs: [build-and-publish]

    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
    - id: set-matrix

      env:
        API_APP_NAME: ${{ vars.API_APP_NAME }}
        WEB_APP_NAME: ${{ vars.WEB_APP_NAME }}

      run: |
        echo "matrix={\"include\":[{\"image\":\"api\",\"app_name\":\"$API_APP_NAME\"},{\"image\":\"web\",\"app_name\":\"$WEB_APP_NAME\"}]}" >> $GITHUB_OUTPUT

  deploy-to-azure:
    name: Deploy to Azure App Service

    runs-on: ubuntu-latest

    needs: [prep-deploy-matrix]

    strategy:
      matrix: ${{ fromJson(needs.prep-deploy-matrix.outputs.matrix) }}

    env:
      TAG_NAME: ${{ format('dev-{0}', github.sha) }}

    steps:

      - name: Azure Login
        uses: azure/login@v2

        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Container to Azure App Service
        uses: azure/webapps-deploy@v3

        with:
          app-name: ${{ matrix.app_name }}

          images: '${{ vars.ACR_URL }}/${{ matrix.image }}:${{ env.TAG_NAME }}'